// Generated by shadow-mode/build.mjs
const FIT_TARGET_HIGH_RATIO = 0.78;
const FIT_TARGET_HIGH_FLOOR = 0.04;
const FIT_TARGET_HIGH_MIN_GAP = 0.05;
const FIT_TARGET_HIGH_CEILING_GAP = 0.02;
const FIT_TARGET_LOW_RATIO = 0.76;
const FIT_TARGET_LOW_FLOOR = 0.02;
const FIT_TARGET_LOW_MIN_GAP = 0.03;
const FIT_TARGET_LOW_CEILING_GAP = 0.02;
const FIT_AUTOREPAY_CEILING_GAP = 0.01;
const FIT_EMERGENCY_MIN_GAP = 0.005;
const CRISIS_WEEKLY_DRAWDOWN = 0.22;
const CRISIS_DAILY_MOVE = 0.12;
const CRISIS_CONFIDENCE_HAIRCUT = 0.75;
const STRESS_WEEKLY_DRAWDOWN = 0.12;
const STRESS_DAILY_MOVE = 0.07;
const STRESS_VOL_30D = 1.10;
const TREND_STRENGTH = 0.65;
const TREND_DAILY_MOVE = 0.035;
const TREND_VOL_30D = 0.75;
const MIN_VENUE_HEALTH_SCORE = 0.5;
const BORROW_HAIRCUT_QUIET = 0.80;
const BORROW_HAIRCUT_TREND = 0.55;
const BORROW_HAIRCUT_STRESS = 0.20;
const BORROW_HAIRCUT_CRISIS = 0.05;
const SHADOW_BASE_HORIZON_DAYS = 30;
const SHADOW_MAX_HORIZON_DAYS = 90;
const SHADOW_LIQUIDATION_PENALTY_BPS_BASE = 500;
const SHADOW_LIQUIDATION_PENALTY_BPS_DRAW = 500;
export const TIDE_PLATFORM_FEE_BPS_ANNUAL = 75;
export var UserMode = /*#__PURE__*/ function(UserMode) {
    UserMode["Income"] = "Income";
    UserMode["StormGuard"] = "StormGuard";
    UserMode["Reserve"] = "Reserve";
    UserMode["Drift"] = "Drift";
    return UserMode;
}({});
export var RiskPriority = /*#__PURE__*/ function(RiskPriority) {
    RiskPriority["Safety"] = "Safety";
    RiskPriority["Stability"] = "Stability";
    RiskPriority["Income"] = "Income";
    RiskPriority["BTCPreservation"] = "BTCPreservation";
    return RiskPriority;
}({});
export var MarketRegime = /*#__PURE__*/ function(MarketRegime) {
    MarketRegime["Quiet"] = "Quiet";
    MarketRegime["Trend"] = "Trend";
    MarketRegime["Stress"] = "Stress";
    MarketRegime["Crisis"] = "Crisis";
    return MarketRegime;
}({});
export var ActionType = /*#__PURE__*/ function(ActionType) {
    ActionType["Hold"] = "Hold";
    ActionType["BuildBuffer"] = "BuildBuffer";
    ActionType["BorrowForBuffer"] = "BorrowForBuffer";
    ActionType["PartialRepay"] = "PartialRepay";
    ActionType["EmergencyDeRisk"] = "EmergencyDeRisk";
    ActionType["ReducePayout"] = "ReducePayout";
    ActionType["PausePayout"] = "PausePayout";
    ActionType["RotateVenue"] = "RotateVenue";
    return ActionType;
}({});
export var OperatingState = /*#__PURE__*/ function(OperatingState) {
    OperatingState["Observe"] = "Observe";
    OperatingState["BuildBuffer"] = "BuildBuffer";
    OperatingState["Maintain"] = "Maintain";
    OperatingState["DeRisk"] = "DeRisk";
    OperatingState["StressLockdown"] = "StressLockdown";
    return OperatingState;
}({});
export class NoopExecutionAdapter {
    async execute(action, _input) {
        return {
            ok: true,
            action,
            txId: `shadow-${Date.now()}`
        };
    }
}
function clamp(value, min, max) {
    return Math.min(max, Math.max(min, value));
}
function safeDiv(a, b) {
    if (b === 0) return 0;
    const result = a / b;
    if (!Number.isFinite(result)) return 0;
    return result;
}
function calculatePortfolioLtv(debtUsd, collateralUsd) {
    if (!Number.isFinite(debtUsd) || debtUsd <= 0) return 0;
    if (!Number.isFinite(collateralUsd) || collateralUsd <= 0) return 1;
    const result = debtUsd / collateralUsd;
    if (!Number.isFinite(result)) return 1;
    return Math.max(0, result);
}
function roundUsd(n) {
    return Math.round(n * 100) / 100;
}
function roundPct(n) {
    return Math.round(n * 10000) / 10000;
}
function average(values) {
    if (values.length === 0) return 0;
    return values.reduce((sum, value)=>sum + value, 0) / values.length;
}
function minValue(values, fallback = 0) {
    return values.length === 0 ? fallback : Math.min(...values);
}
function defaultVenue() {
    return {
        name: "FallbackRail",
        healthy: false,
        oracleConfidence: 0,
        liquidityScore: 0,
        healthScore: 0
    };
}
export function calculateBufferFloor(policy) {
    return Math.max(policy.minStableBufferUsd, policy.monthlyPayoutTargetUsd * policy.desiredRunwayMonths);
}
export function calculateBufferCoverageMonths(stableBufferUsd, monthlyPayoutTargetUsd) {
    return roundUsd(safeDiv(stableBufferUsd, Math.max(1, monthlyPayoutTargetUsd)));
}
function clamp01(value) {
    return clamp(value, 0, 1);
}
function roundBps(n) {
    return Math.round(n);
}
function roundUnits(n) {
    return Math.round(n * 1e8) / 1e8;
}
function toVenueStatus(rail) {
    return {
        name: rail.name,
        healthy: rail.healthy,
        oracleConfidence: rail.oracleConfidence,
        liquidityScore: rail.liquidityScore,
        healthScore: rail.healthScore
    };
}
function normalizeRailThreshold(value, floor, ceiling) {
    return roundPct(clamp(value, floor, ceiling));
}
function fitPolicyToRail(policy, rail) {
    const adjustments = [];
    const maxLtv = Math.min(policy.maxLtv, rail.maxLtv);
    const targetLtvHigh = normalizeRailThreshold(Math.min(policy.targetLtvHigh, maxLtv * FIT_TARGET_HIGH_RATIO), FIT_TARGET_HIGH_FLOOR, Math.max(FIT_TARGET_HIGH_MIN_GAP, maxLtv - FIT_TARGET_HIGH_CEILING_GAP));
    const targetLtvLow = normalizeRailThreshold(Math.min(policy.targetLtvLow, targetLtvHigh * FIT_TARGET_LOW_RATIO), FIT_TARGET_LOW_FLOOR, Math.max(FIT_TARGET_LOW_MIN_GAP, targetLtvHigh - FIT_TARGET_LOW_CEILING_GAP));
    const autoRepayLtv = normalizeRailThreshold(Math.min(Math.max(policy.autoRepayLtv, targetLtvHigh), maxLtv - FIT_AUTOREPAY_CEILING_GAP), targetLtvHigh, maxLtv - FIT_AUTOREPAY_CEILING_GAP);
    const emergencyLtv = normalizeRailThreshold(Math.min(Math.max(policy.emergencyLtv, autoRepayLtv + FIT_EMERGENCY_MIN_GAP), maxLtv), autoRepayLtv, maxLtv);
    const fitted = roundPct(maxLtv);
    if (fitted !== policy.maxLtv) adjustments.push({
        field: "maxLtv",
        original: policy.maxLtv,
        adjusted: fitted,
        reason: `Rail ${rail.name} caps LTV at ${(rail.maxLtv * 100).toFixed(1)}%`
    });
    if (targetLtvHigh !== policy.targetLtvHigh) adjustments.push({
        field: "targetLtvHigh",
        original: policy.targetLtvHigh,
        adjusted: targetLtvHigh,
        reason: "Compressed to fit within rail max LTV"
    });
    if (targetLtvLow !== policy.targetLtvLow) adjustments.push({
        field: "targetLtvLow",
        original: policy.targetLtvLow,
        adjusted: targetLtvLow,
        reason: "Compressed to maintain corridor below targetLtvHigh"
    });
    if (autoRepayLtv !== policy.autoRepayLtv) adjustments.push({
        field: "autoRepayLtv",
        original: policy.autoRepayLtv,
        adjusted: autoRepayLtv,
        reason: "Adjusted to stay within compressed corridor"
    });
    if (emergencyLtv !== policy.emergencyLtv) adjustments.push({
        field: "emergencyLtv",
        original: policy.emergencyLtv,
        adjusted: emergencyLtv,
        reason: "Adjusted to maintain gap above autoRepayLtv"
    });
    return {
        policy: {
            ...policy,
            maxLtv: fitted,
            targetLtvLow,
            targetLtvHigh,
            autoRepayLtv,
            emergencyLtv
        },
        adjustments
    };
}
function applyRailToInput(input, allocation) {
    const primaryRail = allocation?.primary?.rail;
    if (!primaryRail) {
        return input;
    }
    const { policy: fittedPolicy, adjustments } = fitPolicyToRail(input.policy, primaryRail);
    return {
        ...input,
        policy: fittedPolicy,
        venues: [
            toVenueStatus(primaryRail)
        ],
        policyAdjustments: adjustments
    };
}
export class FixtureRailAdapter {
    id;
    label;
    snapshot;
    constructor(snapshot){
        this.id = snapshot.id;
        this.label = snapshot.name;
        this.snapshot = snapshot;
    }
    async fetchSnapshot(context) {
        return {
            ...this.snapshot,
            source: "fixture",
            updatedAt: this.snapshot.updatedAt || new Date(0).toISOString(),
            observedAt: context.now
        };
    }
}
export class SnapshotRailAdapter {
    id;
    label;
    snapshot;
    constructor(snapshot){
        this.id = snapshot.id;
        this.label = snapshot.name;
        this.snapshot = snapshot;
    }
    async fetchSnapshot(_context) {
        return {
            ...this.snapshot
        };
    }
}
export class HttpRailAdapter {
    id;
    label;
    url;
    init;
    mapSnapshot;
    fetcher;
    constructor(options){
        this.id = options.id;
        this.label = options.label;
        this.url = options.url;
        this.init = options.init;
        this.mapSnapshot = options.mapSnapshot;
        this.fetcher = options.fetcher ?? defaultHttpRailFetcher;
    }
    async fetchSnapshot(context) {
        const response = await this.fetcher(this.url, this.init);
        if (!response.ok) {
            throw new Error(`HTTP ${response.status}`);
        }
        const payload = await response.json();
        return this.mapSnapshot(payload, context);
    }
}
async function defaultHttpRailFetcher(url, init) {
    const fetchRef = globalThis.fetch;
    if (typeof fetchRef !== "function") {
        throw new Error("Global fetch is not available in this runtime.");
    }
    return fetchRef(url, init);
}
export class RailSnapshotAggregator {
    async collect(adapters, context) {
        const snapshots = [];
        const warnings = [];
        for (const adapter of adapters){
            try {
                snapshots.push(await adapter.fetchSnapshot(context));
            } catch (error) {
                const message = error instanceof Error ? error.message : "Unknown adapter error";
                warnings.push(`${adapter.label} snapshot failed: ${message}`);
            }
        }
        return {
            snapshots,
            warnings
        };
    }
}
export class RailAllocator {
    allocate(context, rails, inheritedWarnings = []) {
        if (rails.length === 0) {
            return {
                ranked: [],
                warnings: [
                    ...inheritedWarnings,
                    "No rail snapshots are available."
                ]
            };
        }
        const weights = {
            ["Safety"]: {
                health: 34,
                liquidity: 20,
                oracle: 16,
                leverage: 12,
                apr: 8,
                depth: 8,
                cost: 2
            },
            ["Stability"]: {
                health: 28,
                liquidity: 20,
                oracle: 14,
                leverage: 14,
                apr: 12,
                depth: 8,
                cost: 4
            },
            ["Income"]: {
                health: 20,
                liquidity: 16,
                oracle: 12,
                leverage: 12,
                apr: 24,
                depth: 10,
                cost: 6
            },
            ["BTCPreservation"]: {
                health: 32,
                liquidity: 18,
                oracle: 14,
                leverage: 16,
                apr: 10,
                depth: 8,
                cost: 2
            }
        }[context.policy.priority];
        const desiredDebtUsd = Math.max(context.portfolio.debtUsd, context.policy.monthlyPayoutTargetUsd * context.policy.desiredRunwayMonths);
        const preferredRailKey = normalizePreferredRailId(context.policy.preferredRailId);
        const ranked = [
            ...rails
        ].map((rail)=>{
            const reasons = [];
            const healthScore = clamp01(rail.healthScore);
            const liquidityScore = clamp01(rail.liquidityScore);
            const oracleScore = clamp01(rail.oracleConfidence);
            const leverageScore = clamp01(safeDiv(rail.maxLtv, Math.max(0.01, context.policy.maxLtv)));
            const aprScore = 1 - clamp01(safeDiv(rail.borrowApr, 0.18));
            const depthScore = clamp01(safeDiv(rail.availableDebtUsd, Math.max(1, desiredDebtUsd)));
            const costScore = 1 - clamp01(safeDiv(rail.rebalanceCostBps, 160));
            let score = healthScore * weights.health + liquidityScore * weights.liquidity + oracleScore * weights.oracle + leverageScore * weights.leverage + aprScore * weights.apr + depthScore * weights.depth + costScore * weights.cost;
            if (!rail.healthy) {
                score -= 18;
                reasons.push("Venue health is currently below the operating floor.");
            }
            if (rail.maxLtv < context.policy.targetLtvHigh) {
                score -= 8;
                reasons.push("Rail max LTV compresses the requested operating corridor.");
            } else {
                reasons.push("Rail can support the requested operating corridor.");
            }
            if (rail.borrowApr <= 0.055) {
                reasons.push("Borrow cost is competitive for income extraction.");
            } else if (rail.borrowApr >= 0.075) {
                reasons.push("Borrow cost is elevated, so cashflow margin is tighter.");
            }
            if (rail.availableDebtUsd < desiredDebtUsd) {
                score -= 6;
                reasons.push("Available debt depth is tight for the requested setup.");
            } else {
                reasons.push("Debt depth is sufficient for the requested setup.");
            }
            if (rail.rebalanceCostBps <= 20) {
                reasons.push("Rebalance friction is low enough for backup routing.");
            }
            if (rail.tags.length > 0) {
                reasons.push(`Profile: ${rail.tags.join(", ")}.`);
            }
            return {
                rail,
                score: Math.round(score),
                recommendedRole: "Avoid",
                reasons
            };
        }).sort((a, b)=>b.score - a.score);
        const preferredPrimary = preferredRailKey ? ranked.find((scorecard)=>railMatchesPreference(scorecard.rail, preferredRailKey) && scorecard.rail.healthy && scorecard.rail.healthScore >= 0.62 && scorecard.rail.oracleConfidence >= context.policy.minOracleConfidence * 0.92) : null;
        const primary = preferredPrimary ?? ranked.find((scorecard)=>{
            return scorecard.rail.healthy && scorecard.rail.healthScore >= 0.62 && scorecard.rail.oracleConfidence >= context.policy.minOracleConfidence * 0.92;
        }) ?? ranked[0];
        let backup = ranked.find((scorecard)=>{
            return scorecard.rail.id !== primary?.rail.id && scorecard.rail.wrapper !== primary?.rail.wrapper && scorecard.rail.healthy && scorecard.rail.healthScore >= 0.56 && scorecard.rail.liquidityScore >= context.policy.minLiquidityScore;
        });
        if (!backup) {
            backup = ranked.find((scorecard)=>scorecard.rail.id !== primary?.rail.id);
        }
        const warnings = [
            ...inheritedWarnings
        ];
        if (!primary?.rail.healthy) {
            warnings.push("Primary rail candidate is not fully healthy; fallback logic is likely required.");
        }
        if (primary && primary.rail.maxLtv < context.policy.maxLtv) {
            warnings.push(`${primary.rail.name} caps max LTV at ${(primary.rail.maxLtv * 100).toFixed(1)}%, below the requested ${(context.policy.maxLtv * 100).toFixed(1)}%.`);
        }
        if (!backup) {
            warnings.push("No backup rail met the safety floor; routing remains single-rail fragile.");
        }
        const annotated = ranked.map((scorecard)=>{
            if (primary && scorecard.rail.id === primary.rail.id) {
                return {
                    ...scorecard,
                    recommendedRole: "Primary"
                };
            }
            if (backup && scorecard.rail.id === backup.rail.id) {
                return {
                    ...scorecard,
                    recommendedRole: "Backup"
                };
            }
            return scorecard;
        });
        return {
            primary: annotated.find((scorecard)=>scorecard.recommendedRole === "Primary"),
            backup: annotated.find((scorecard)=>scorecard.recommendedRole === "Backup"),
            ranked: annotated,
            warnings
        };
    }
}
function normalizePreferredRailId(value) {
    return String(value || "").trim().toLowerCase().replace(/-sui$/, "");
}
function railMatchesPreference(rail, preference) {
    if (!preference) return false;
    const railIds = [
        rail.id,
        rail.name
    ].map((value)=>String(value || "").trim().toLowerCase().replace(/-sui$/, "")).filter(Boolean);
    return railIds.includes(preference);
}
function assertPolicy(policy) {
    const checks = [
        [
            policy.maxLtv > 0 && policy.maxLtv < 1,
            "maxLtv must be between 0 and 1"
        ],
        [
            policy.targetLtvLow >= 0 && policy.targetLtvLow < policy.targetLtvHigh,
            "targetLtvLow must be < targetLtvHigh"
        ],
        [
            policy.targetLtvHigh < policy.maxLtv,
            "targetLtvHigh must be below maxLtv"
        ],
        [
            policy.autoRepayLtv >= policy.targetLtvHigh && policy.autoRepayLtv <= policy.maxLtv,
            "autoRepayLtv must be between targetLtvHigh and maxLtv"
        ],
        [
            policy.emergencyLtv >= policy.autoRepayLtv && policy.emergencyLtv <= policy.maxLtv,
            "emergencyLtv must be between autoRepayLtv and maxLtv"
        ],
        [
            policy.minOracleConfidence >= 0 && policy.minOracleConfidence <= 1,
            "minOracleConfidence must be 0..1"
        ],
        [
            policy.minLiquidityScore >= 0 && policy.minLiquidityScore <= 1,
            "minLiquidityScore must be 0..1"
        ],
        [
            policy.maxSingleVenueExposurePct > 0 && policy.maxSingleVenueExposurePct <= 1,
            "maxSingleVenueExposurePct must be 0..1"
        ],
        [
            policy.maxWrapperExposurePct > 0 && policy.maxWrapperExposurePct <= 1,
            "maxWrapperExposurePct must be 0..1"
        ],
        [
            policy.monthlyPayoutTargetUsd >= 0,
            "monthlyPayoutTargetUsd must be >= 0"
        ],
        [
            policy.minStableBufferUsd >= 0,
            "minStableBufferUsd must be >= 0"
        ],
        [
            policy.desiredRunwayMonths > 0,
            "desiredRunwayMonths must be > 0"
        ]
    ];
    for (const [ok, message] of checks){
        if (!ok) throw new Error(`Invalid policy: ${message}`);
    }
}
export class RegimeEngine {
    classify(market, venues, policy) {
        if (venues.length === 0) {
            return "Crisis";
        }
        const worstVenueHealth = Math.min(...venues.map((v)=>v.healthScore));
        const worstOracle = Math.min(...venues.map((v)=>v.oracleConfidence));
        const worstLiquidity = Math.min(...venues.map((v)=>v.liquidityScore));
        const anyVenueDown = venues.some((v)=>!v.healthy);
        if (anyVenueDown || worstOracle < policy.minOracleConfidence * CRISIS_CONFIDENCE_HAIRCUT || worstLiquidity < policy.minLiquidityScore * CRISIS_CONFIDENCE_HAIRCUT || market.weeklyDrawdownPct >= CRISIS_WEEKLY_DRAWDOWN || market.dailyMovePctAbs >= CRISIS_DAILY_MOVE) {
            return "Crisis";
        }
        if (worstOracle < policy.minOracleConfidence || worstLiquidity < policy.minLiquidityScore || market.weeklyDrawdownPct >= STRESS_WEEKLY_DRAWDOWN || market.dailyMovePctAbs >= STRESS_DAILY_MOVE || market.realizedVol30d >= STRESS_VOL_30D) {
            return "Stress";
        }
        if (market.trendStrength >= TREND_STRENGTH || market.dailyMovePctAbs >= TREND_DAILY_MOVE || market.realizedVol30d >= TREND_VOL_30D) {
            return "Trend";
        }
        return "Quiet";
    }
}
export class RiskEngine {
    evaluate(input, regime) {
        const { policy, portfolio, venues } = input;
        const venueSet = venues.length > 0 ? venues : [
            defaultVenue()
        ];
        const ltv = calculatePortfolioLtv(portfolio.debtUsd, portfolio.collateralUsd);
        if (!Number.isFinite(ltv) || ltv < 0) {
            throw new Error(`Invalid LTV state: debt=${portfolio.debtUsd}, collateral=${portfolio.collateralUsd}, ltv=${ltv}`);
        }
        const oracleHealthy = venueSet.every((v)=>v.oracleConfidence >= policy.minOracleConfidence);
        const liquidityHealthy = venueSet.every((v)=>v.liquidityScore >= policy.minLiquidityScore);
        const venueHealthy = venueSet.every((v)=>v.healthy && v.healthScore >= MIN_VENUE_HEALTH_SCORE);
        const liquidationDistancePct = clamp(safeDiv(policy.maxLtv - ltv, policy.maxLtv), 0, 1);
        const bufferFloor = calculateBufferFloor(policy);
        const bufferShortfallUsd = Math.max(0, bufferFloor - portfolio.stableBufferUsd);
        const regimeBorrowHaircut = {
            ["Quiet"]: BORROW_HAIRCUT_QUIET,
            ["Trend"]: BORROW_HAIRCUT_TREND,
            ["Stress"]: policy.allowNewBorrowInStress ? BORROW_HAIRCUT_STRESS : 0.00,
            ["Crisis"]: policy.allowNewBorrowInCrisis ? BORROW_HAIRCUT_CRISIS : 0.00
        }[regime];
        const safeHeadroomUsd = Math.max(0, portfolio.collateralUsd * policy.targetLtvHigh - portfolio.debtUsd) * regimeBorrowHaircut;
        const sustainableMonthlyPayoutUsd = roundUsd(Math.min(policy.monthlyPayoutTargetUsd, Math.max(0, (portfolio.stableBufferUsd + safeHeadroomUsd) / Math.max(1, policy.desiredRunwayMonths))));
        return {
            ltv,
            liquidationDistancePct,
            oracleHealthy,
            liquidityHealthy,
            venueHealthy,
            bufferShortfallUsd: roundUsd(bufferShortfallUsd),
            safeHeadroomUsd: roundUsd(safeHeadroomUsd),
            sustainableMonthlyPayoutUsd,
            venueConcentrationBreach: portfolio.venueExposurePct > policy.maxSingleVenueExposurePct,
            wrapperConcentrationBreach: portfolio.wrapperExposurePct > policy.maxWrapperExposurePct,
            needsRepay: ltv >= policy.autoRepayLtv,
            needsEmergencyDeRisk: ltv >= policy.emergencyLtv || regime === "Crisis" || !oracleHealthy || !venueHealthy
        };
    }
}
export class Planner {
    plan(input, regime, risk) {
        const { policy, portfolio } = input;
        const actions = [];
        if (risk.needsEmergencyDeRisk) {
            const targetDebtUsd = portfolio.collateralUsd * policy.targetLtvLow;
            const repayAmountUsd = roundUsd(Math.max(0.01, portfolio.debtUsd - targetDebtUsd));
            const chosen = {
                type: "EmergencyDeRisk",
                amountUsd: repayAmountUsd,
                reason: "Emergency risk condition detected",
                explanation: "TIDE detected a crisis-level risk signal or unhealthy infrastructure state. " + "The rehearsal plan would prioritize survival, reduce debt, and protect the BTC core.",
                metadata: {
                    regime,
                    currentLtv: risk.ltv,
                    targetLtvLow: policy.targetLtvLow
                }
            };
            actions.push(chosen);
            if (policy.allowPayoutPauseInStress) {
                actions.push({
                    type: "PausePayout",
                    reason: "Preserve liquidity during emergency mode",
                    explanation: "Payouts are paused to preserve stable buffer and avoid pushing the position closer to unsafe leverage.",
                    metadata: {
                        regime
                    }
                });
            }
            return {
                regime,
                risk,
                actions,
                chosen
            };
        }
        if (risk.needsRepay) {
            const targetDebtUsd = portfolio.collateralUsd * policy.targetLtvLow;
            const repayAmountUsd = roundUsd(Math.max(0, portfolio.debtUsd - targetDebtUsd));
            const chosen = {
                type: "PartialRepay",
                amountUsd: repayAmountUsd,
                reason: "LTV exceeded auto-repay threshold",
                explanation: "The current leverage moved above your auto-repay threshold. " + "The rehearsal plan would reduce debt before the position approaches unsafe territory.",
                metadata: {
                    currentLtv: risk.ltv,
                    autoRepayLtv: policy.autoRepayLtv,
                    targetLtvLow: policy.targetLtvLow
                }
            };
            actions.push(chosen);
            return {
                regime,
                risk,
                actions,
                chosen
            };
        }
        if (risk.bufferShortfallUsd > 0) {
            const canBorrow = regime !== "Crisis" && (regime !== "Stress" || policy.allowNewBorrowInStress);
            const borrowableBufferUsd = roundUsd(Math.min(risk.bufferShortfallUsd, Math.max(0, risk.safeHeadroomUsd)));
            const chosen = canBorrow && borrowableBufferUsd > 0 ? {
                type: "BorrowForBuffer",
                amountUsd: borrowableBufferUsd,
                reason: "Stable buffer below policy minimum",
                explanation: "The stable buffer is below your required floor. " + "TIDE is rebuilding the buffer only within modeled safe borrowing headroom.",
                metadata: {
                    shortfallUsd: risk.bufferShortfallUsd,
                    safeHeadroomUsd: risk.safeHeadroomUsd,
                    unmetShortfallUsd: roundUsd(Math.max(0, risk.bufferShortfallUsd - borrowableBufferUsd)),
                    regime
                }
            } : {
                type: "BuildBuffer",
                amountUsd: risk.bufferShortfallUsd,
                reason: "Stable buffer below policy minimum; new borrowing restricted",
                explanation: "The engine needs to rebuild the stable buffer, but current regime rules restrict fresh borrowing. " + "Priority shifts to preserving cash and rebuilding liquidity conservatively.",
                metadata: {
                    shortfallUsd: risk.bufferShortfallUsd,
                    regime
                }
            };
            actions.push(chosen);
            return {
                regime,
                risk,
                actions,
                chosen
            };
        }
        if (risk.venueConcentrationBreach || risk.wrapperConcentrationBreach) {
            const chosen = {
                type: "RotateVenue",
                reason: "Concentration rule breached",
                explanation: "Exposure to a single venue or wrapper exceeded your configured concentration limits. " + "TIDE recommends rotating exposure to restore policy compliance.",
                metadata: {
                    venueBreach: risk.venueConcentrationBreach,
                    wrapperBreach: risk.wrapperConcentrationBreach
                }
            };
            actions.push(chosen);
            return {
                regime,
                risk,
                actions,
                chosen
            };
        }
        if (policy.mode === "Income" && risk.sustainableMonthlyPayoutUsd < policy.monthlyPayoutTargetUsd) {
            const chosen = {
                type: "ReducePayout",
                amountUsd: roundUsd(policy.monthlyPayoutTargetUsd - risk.sustainableMonthlyPayoutUsd),
                reason: "Current payout target is not sustainable under present conditions",
                explanation: "TIDE estimates your current payout target is above the sustainable band for the current risk regime. " + "Reducing payout helps preserve BTC upside while keeping leverage under control.",
                metadata: {
                    targetPayoutUsd: policy.monthlyPayoutTargetUsd,
                    sustainablePayoutUsd: risk.sustainableMonthlyPayoutUsd,
                    regime
                }
            };
            actions.push(chosen);
            return {
                regime,
                risk,
                actions,
                chosen
            };
        }
        if (policy.mode === "StormGuard" && risk.ltv > policy.targetLtvLow) {
            const repayAmountUsd = roundUsd(Math.max(0, portfolio.debtUsd - portfolio.collateralUsd * policy.targetLtvLow));
            const chosen = {
                type: "PartialRepay",
                amountUsd: repayAmountUsd,
                reason: "Storm Guard prioritizes survivability over extraction",
                explanation: "Storm Guard mode is proactively pushing leverage down toward the lower end of your policy band " + "to increase survival margin under volatility expansion.",
                metadata: {
                    currentLtv: risk.ltv,
                    targetLtvLow: policy.targetLtvLow
                }
            };
            actions.push(chosen);
            return {
                regime,
                risk,
                actions,
                chosen
            };
        }
        const chosen = {
            type: "Hold",
            reason: "Position is inside policy band",
            explanation: "No intervention is required right now. The position remains within risk, buffer, and policy constraints.",
            metadata: {
                regime,
                currentLtv: risk.ltv,
                sustainablePayoutUsd: risk.sustainableMonthlyPayoutUsd
            }
        };
        actions.push(chosen);
        return {
            regime,
            risk,
            actions,
            chosen
        };
    }
}
export class TideEngine {
    regimeEngine = new RegimeEngine();
    riskEngine = new RiskEngine();
    planner = new Planner();
    async tick(input, opts) {
        assertPolicy(input.policy);
        const regime = this.regimeEngine.classify(input.market, input.venues, input.policy);
        const risk = this.riskEngine.evaluate(input, regime);
        const decision = this.planner.plan(input, regime, risk);
        if (opts?.execute) {
            const adapter = opts.adapter ?? new NoopExecutionAdapter();
            const receipt = await adapter.execute(decision.chosen, input);
            return {
                input,
                decision,
                receipt
            };
        }
        return {
            input,
            decision
        };
    }
    async runShadow(inputs) {
        const results = [];
        for (const input of inputs){
            results.push(await this.tick(input, {
                execute: false
            }));
        }
        return results;
    }
}
const SUI_BTCFI_SOURCE_URL = "https://www.sui.io/btcfi-bitcoin-defi-on-sui";
const SUI_BTCFI_BLOG_URL = "https://blog.sui.io/bitcoin-defi-opportunities-on-sui/";
const FERRA_DOCS_URL = "https://docs.ferra.ag/";
const FERRA_AGGREGATOR_URL = "https://docs.ferra.ag/integration/aggregator-internal-deprecated/typescript-sdk/overview";
const KRIYA_APP_URL = "https://kriya.finance/";
const KRIYA_WBTC_SOURCE_URL = "https://docs.kriya.finance/kriya-swap/swap-tutorial/trade/limit-order";
const HOP_DOCS_URL = "https://docs.hop.ag/";
const HOP_SDK_URL = "https://docs.hop.ag/hop-sdk";
export const OFFICIAL_SUI_BTCFI_PROTOCOLS = [
    {
        id: "7k",
        name: "7K",
        category: "TradeLP",
        description: "BTC trading aggregator with pools, limit orders, DCA, and bridge routing.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "LBTC",
            "stBTC"
        ],
        capabilities: [
            "Aggregation",
            "DCA",
            "LimitOrders",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "aftermath",
        name: "Aftermath",
        category: "Routing",
        description: "DCA, TWAP, and deep-routing execution across BTC liquidity venues.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "LBTC"
        ],
        capabilities: [
            "Aggregation",
            "DCA",
            "DeepLiquidity",
            "Swaps",
            "TWAP"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "astros",
        name: "Astros",
        category: "Lending",
        description: "Advanced lending and looping venue included in Sui's BTCfi stack.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_SOURCE_URL,
        supportedBtcAssets: [],
        capabilities: [
            "Borrow",
            "Collateral",
            "Leverage",
            "Lending"
        ],
        treasuryRailRole: "CoreRail",
        adapterStatus: "fixture"
    },
    {
        id: "bluefin",
        name: "Bluefin",
        category: "Derivatives",
        description: "Perps venue for BTC directional positioning and hedge overlays.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "xBTC",
            "AUSD",
            "USDC"
        ],
        capabilities: [
            "Perps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "bucket",
        name: "Bucket Protocol",
        category: "Lending",
        description: "Borrowing, leverage, and BTC collateral management venue.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC"
        ],
        capabilities: [
            "Borrow",
            "Collateral",
            "Leverage",
            "Lending"
        ],
        treasuryRailRole: "CoreRail",
        adapterStatus: "fixture"
    },
    {
        id: "cetus",
        name: "Cetus",
        category: "TradeLP",
        description: "CLMM and BTC liquidity venue on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "LBTC",
            "xBTC"
        ],
        capabilities: [
            "AMM",
            "LP",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "deepbook",
        name: "DeepBook",
        category: "LiquidityLayer",
        description: "Shared liquidity layer that supports BTC routing depth across Sui apps.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_SOURCE_URL,
        supportedBtcAssets: [],
        capabilities: [
            "DeepLiquidity",
            "UnifiedLiquidity"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "flowx",
        name: "FlowX",
        category: "TradeLP",
        description: "BTC spot venue and LP surface on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC"
        ],
        capabilities: [
            "AMM",
            "LP",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "magma",
        name: "Magma",
        category: "Routing",
        description: "BTC routing and strategy access point across Sui liquidity.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "xBTC",
            "LBTC",
            "AUSD",
            "USDC"
        ],
        capabilities: [
            "Aggregation",
            "LP",
            "Swaps"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    },
    {
        id: "momentum",
        name: "Momentum",
        category: "TradeLP",
        description: "BTC liquidity and market venue on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "LBTC",
            "AUSD",
            "USDC"
        ],
        capabilities: [
            "LP",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "steamm",
        name: "Steamm",
        category: "TradeLP",
        description: "BTC liquidity pools and trading venue on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "WBTC"
        ],
        capabilities: [
            "AMM",
            "LP",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "turbos",
        name: "Turbos",
        category: "TradeLP",
        description: "BTC CLMM venue with concentrated liquidity on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "xBTC",
            "LBTC"
        ],
        capabilities: [
            "AMM",
            "LP",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "typus",
        name: "Typus",
        category: "Derivatives",
        description: "Options and structured BTC strategies on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC"
        ],
        capabilities: [
            "Options",
            "Yield"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    },
    {
        id: "alphalend",
        name: "AlphaLend",
        category: "Lending",
        description: "BTC lending and leverage venue on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "LBTC"
        ],
        capabilities: [
            "Borrow",
            "Collateral",
            "Leverage",
            "Lending"
        ],
        treasuryRailRole: "CoreRail",
        adapterStatus: "fixture"
    },
    {
        id: "kai-finance",
        name: "Kai Finance",
        category: "Lending",
        description: "BTC-backed borrowing and leverage venue on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC"
        ],
        capabilities: [
            "Borrow",
            "Collateral",
            "Leverage",
            "Lending"
        ],
        treasuryRailRole: "CoreRail",
        adapterStatus: "fixture"
    },
    {
        id: "navi",
        name: "NAVI Protocol",
        category: "Lending",
        description: "Major BTC lending and borrowing venue on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "LBTC",
            "stBTC"
        ],
        capabilities: [
            "Borrow",
            "Collateral",
            "Leverage",
            "Lending"
        ],
        treasuryRailRole: "CoreRail",
        adapterStatus: "fixture"
    },
    {
        id: "suilend",
        name: "Suilend",
        category: "Lending",
        description: "BTC lending and borrow venue with treasury-relevant collateral rails.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "LBTC",
            "stBTC"
        ],
        capabilities: [
            "Borrow",
            "Collateral",
            "Lending"
        ],
        treasuryRailRole: "CoreRail",
        adapterStatus: "fixture"
    },
    {
        id: "alphafi",
        name: "AlphaFi",
        category: "Vaults",
        description: "BTC vault strategies and managed collateral surfaces on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC"
        ],
        capabilities: [
            "StrategyVaults",
            "Yield"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    },
    {
        id: "haedal",
        name: "Haedal",
        category: "Vaults",
        description: "Vault and auto-compound surface that includes BTC positions.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "haSUI",
            "USDC",
            "wBTC"
        ],
        capabilities: [
            "AutoCompound",
            "StrategyVaults",
            "Yield"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    },
    {
        id: "lotus-finance",
        name: "Lotus Finance",
        category: "Vaults",
        description: "BTC and stablecoin vault strategies on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "xBTC",
            "USDC"
        ],
        capabilities: [
            "StrategyVaults",
            "Yield"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    },
    {
        id: "metastable",
        name: "Metastable",
        category: "Vaults",
        description: "BTC vault strategies and structured LP surfaces.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_BLOG_URL,
        supportedBtcAssets: [
            "wBTC",
            "USDC"
        ],
        capabilities: [
            "StrategyVaults",
            "Yield"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    },
    {
        id: "native",
        name: "Native",
        category: "Routing",
        description: "BTC ingress and routing layer for moving BTC into Sui DeFi rails.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_SOURCE_URL,
        supportedBtcAssets: [
            "nBTC"
        ],
        capabilities: [
            "BridgeIngress",
            "Collateral",
            "Swaps"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    },
    {
        id: "nemo",
        name: "Nemo",
        category: "Vaults",
        description: "BTCfi access layer with zap deposit, staking, and auto-compound strategies.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_SOURCE_URL,
        supportedBtcAssets: [],
        capabilities: [
            "Aggregation",
            "AutoCompound",
            "BridgeIngress",
            "StrategyVaults",
            "Yield"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    },
    {
        id: "scallop",
        name: "Scallop",
        category: "Lending",
        description: "Lending market with BTC asset support on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_SOURCE_URL,
        supportedBtcAssets: [],
        capabilities: [
            "Borrow",
            "Collateral",
            "Lending"
        ],
        treasuryRailRole: "CoreRail",
        adapterStatus: "fixture"
    },
    {
        id: "volo",
        name: "Volo",
        category: "Vaults",
        description: "Vault product set that expands BTC strategy surfaces on Sui.",
        referenceUrl: SUI_BTCFI_SOURCE_URL,
        sourceUrl: SUI_BTCFI_SOURCE_URL,
        supportedBtcAssets: [],
        capabilities: [
            "StrategyVaults",
            "Yield"
        ],
        treasuryRailRole: "SupportingRail",
        adapterStatus: "fixture"
    }
];
export const ECOSYSTEM_EXTENSION_PROTOCOLS = [
    {
        id: "ferra",
        name: "Ferra",
        category: "LiquidityLayer",
        description: "Native Sui liquidity and routing layer with DLMM, CLMM, DAMM, and internal aggregation.",
        referenceUrl: FERRA_DOCS_URL,
        sourceUrl: FERRA_AGGREGATOR_URL,
        supportedBtcAssets: [],
        capabilities: [
            "Aggregation",
            "AMM",
            "DeepLiquidity",
            "LP",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "kriya",
        name: "Kriya",
        category: "TradeLP",
        description: "Sui-native swap and strategy venue with documented WBTC/USDC trading and cross-protocol vault surfaces.",
        referenceUrl: KRIYA_APP_URL,
        sourceUrl: KRIYA_WBTC_SOURCE_URL,
        supportedBtcAssets: [
            "wBTC"
        ],
        capabilities: [
            "AMM",
            "DeepLiquidity",
            "LimitOrders",
            "LP",
            "StrategyVaults",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "planned"
    },
    {
        id: "hop-aggregator",
        name: "Hop Aggregator",
        category: "Routing",
        description: "Sui-native aggregation layer routing liquidity across venues, relevant for BTC execution paths and best-price discovery.",
        referenceUrl: HOP_DOCS_URL,
        sourceUrl: HOP_SDK_URL,
        supportedBtcAssets: [],
        capabilities: [
            "Aggregation",
            "DeepLiquidity",
            "Swaps"
        ],
        treasuryRailRole: "SupportOnly",
        adapterStatus: "http_ready"
    }
];
export const SUI_BTCFI_PROTOCOLS = [
    ...OFFICIAL_SUI_BTCFI_PROTOCOLS,
    ...ECOSYSTEM_EXTENSION_PROTOCOLS
];
export function getOfficialSuiBtcfiProtocols() {
    return OFFICIAL_SUI_BTCFI_PROTOCOLS.slice();
}
export function getEcosystemExtensionProtocols() {
    return ECOSYSTEM_EXTENSION_PROTOCOLS.slice();
}
export function getTreasuryRailProtocols() {
    return SUI_BTCFI_PROTOCOLS.filter((protocol)=>protocol.treasuryRailRole !== "SupportOnly");
}
function protocolHasCapability(protocol, capability) {
    return protocol.capabilities.includes(capability);
}
function buildModeledRailSnapshot(protocol, index) {
    const categoryDefaults = {
        Lending: {
            healthScore: 0.90,
            liquidityScore: 0.87,
            oracleConfidence: 0.96,
            borrowApr: 0.061,
            depositApr: 0.014,
            maxLtv: 0.35,
            availableDebtUsd: 2500000,
            rebalanceCostBps: 13
        },
        Vaults: {
            healthScore: 0.84,
            liquidityScore: 0.78,
            oracleConfidence: 0.93,
            borrowApr: 0.069,
            depositApr: 0.022,
            maxLtv: 0.28,
            availableDebtUsd: 1350000,
            rebalanceCostBps: 19
        },
        Routing: {
            healthScore: 0.82,
            liquidityScore: 0.81,
            oracleConfidence: 0.92,
            borrowApr: 0.066,
            depositApr: 0.018,
            maxLtv: 0.27,
            availableDebtUsd: 1250000,
            rebalanceCostBps: 17
        },
        TradeLP: {
            healthScore: 0.79,
            liquidityScore: 0.83,
            oracleConfidence: 0.91,
            borrowApr: 0.073,
            depositApr: 0.01,
            maxLtv: 0.24,
            availableDebtUsd: 900000,
            rebalanceCostBps: 24
        },
        Derivatives: {
            healthScore: 0.77,
            liquidityScore: 0.79,
            oracleConfidence: 0.9,
            borrowApr: 0.076,
            depositApr: 0.009,
            maxLtv: 0.2,
            availableDebtUsd: 700000,
            rebalanceCostBps: 28
        },
        LiquidityLayer: {
            healthScore: 0.8,
            liquidityScore: 0.88,
            oracleConfidence: 0.92,
            borrowApr: 0.071,
            depositApr: 0.011,
            maxLtv: 0.22,
            availableDebtUsd: 1100000,
            rebalanceCostBps: 22
        }
    }[protocol.category];
    const variation = (index % 5 - 2) * 0.012;
    const healthy = categoryDefaults.healthScore + variation >= 0.62;
    const maxLtvBoost = protocolHasCapability(protocol, "Leverage") ? 0.03 : 0;
    const borrowAprDiscount = protocolHasCapability(protocol, "Borrow") ? 0.005 : 0;
    const depthBoost = protocolHasCapability(protocol, "DeepLiquidity") ? 650000 : 0;
    const wrapper = protocol.supportedBtcAssets[0] ?? "BTC basket";
    const stableAsset = protocol.supportedBtcAssets.includes("AUSD") ? "AUSD" : "USDC";
    return {
        id: protocol.id,
        name: protocol.name,
        source: "fixture",
        wrapper,
        stableAsset,
        healthy,
        oracleConfidence: roundPct(clamp(categoryDefaults.oracleConfidence + variation * 0.55, 0.45, 0.99)),
        liquidityScore: roundPct(clamp(categoryDefaults.liquidityScore + variation * 0.8, 0.18, 0.99)),
        healthScore: roundPct(clamp(categoryDefaults.healthScore + variation, 0.12, 0.99)),
        borrowApr: roundPct(clamp(categoryDefaults.borrowApr - borrowAprDiscount + variation * 0.3, 0.02, 0.2)),
        depositApr: roundPct(clamp(categoryDefaults.depositApr + variation * 0.15, 0, 0.2)),
        maxLtv: roundPct(clamp(categoryDefaults.maxLtv + maxLtvBoost + variation * 0.4, 0.12, 0.75)),
        availableDebtUsd: roundUsd(Math.max(250000, categoryDefaults.availableDebtUsd + depthBoost + (index - 3) * 180000)),
        rebalanceCostBps: roundBps(Math.max(6, categoryDefaults.rebalanceCostBps + index * 2 - (protocolHasCapability(protocol, "Aggregation") ? 3 : 0))),
        supportsRefinance: protocolHasCapability(protocol, "Borrow") || protocolHasCapability(protocol, "Lending") || protocolHasCapability(protocol, "Aggregation"),
        tags: [
            protocol.category,
            ...protocol.capabilities.slice(0, 2)
        ],
        notes: [
            `Modeled starter fixture for ${protocol.name}; not live protocol data.`,
            `Reference: ${protocol.referenceUrl}`
        ],
        updatedAt: new Date(0).toISOString()
    };
}
export const STARTER_RAIL_FIXTURES = getTreasuryRailProtocols().map((protocol, index)=>buildModeledRailSnapshot(protocol, index));
export function createStarterRailAdapters() {
    return STARTER_RAIL_FIXTURES.map((snapshot)=>new FixtureRailAdapter(snapshot));
}
export function createSnapshotRailAdapters(snapshots) {
    return snapshots.map((snapshot)=>new SnapshotRailAdapter(snapshot));
}
export const DEFAULT_SHADOW_SCENARIOS = [
    {
        id: "current",
        label: "Current setup",
        drawdownPct: 0,
        horizonDays: 30
    },
    {
        id: "pullback",
        label: "-20% drawdown",
        drawdownPct: 0.20,
        horizonDays: 45
    },
    {
        id: "stress",
        label: "-35% drawdown",
        drawdownPct: 0.35,
        horizonDays: 60
    },
    {
        id: "crash",
        label: "-50% drawdown",
        drawdownPct: 0.50,
        horizonDays: 90
    },
    {
        id: "oracle-stale",
        label: "Oracle confidence drop",
        drawdownPct: 0,
        horizonDays: 30,
        oracleConfidenceHaircut: 0.30
    },
    {
        id: "stable-depeg",
        label: "Stable buffer depeg",
        drawdownPct: 0.15,
        horizonDays: 45,
        stableDepegPct: 0.05
    }
];
const OPERATING_STATE_SEVERITY = {
    ["Observe"]: 0,
    ["Maintain"]: 1,
    ["BuildBuffer"]: 2,
    ["DeRisk"]: 3,
    ["StressLockdown"]: 4
};
export function deriveOperatingState(input, decision) {
    const hasPauseAction = decision.actions.some((action)=>action.type === "PausePayout");
    if (decision.regime === "Crisis" || decision.chosen.type === "EmergencyDeRisk" || hasPauseAction) {
        return "StressLockdown";
    }
    if (decision.chosen.type === "BorrowForBuffer" || decision.chosen.type === "BuildBuffer") {
        return "BuildBuffer";
    }
    if (decision.regime === "Stress" || decision.chosen.type === "PartialRepay" || decision.chosen.type === "RotateVenue" || decision.chosen.type === "ReducePayout") {
        return "DeRisk";
    }
    if (!input.portfolio.lastActionAt && decision.regime === "Quiet" && decision.risk.ltv < input.policy.targetLtvLow * 0.85) {
        return "Observe";
    }
    return "Maintain";
}
export function evaluatePolicyHealth(input, decision) {
    const { policy } = input;
    const { risk, regime } = decision;
    const notes = [];
    const bufferFloor = calculateBufferFloor(policy);
    const ltvPressure = clamp(safeDiv(risk.ltv, policy.maxLtv), 0, 1);
    const bufferStress = clamp(safeDiv(risk.bufferShortfallUsd, Math.max(1, bufferFloor)), 0, 1);
    let score = 100;
    score -= ltvPressure * 32;
    score -= bufferStress * 28;
    const regimePenalty = {
        ["Quiet"]: 0,
        ["Trend"]: 8,
        ["Stress"]: 18,
        ["Crisis"]: 32
    }[regime];
    score -= regimePenalty;
    if (!risk.oracleHealthy) {
        score -= 14;
        notes.push("Oracle confidence is below the minimum threshold.");
    }
    if (!risk.liquidityHealthy) {
        score -= 10;
        notes.push("Execution liquidity is below the policy floor.");
    }
    if (!risk.venueHealthy) {
        score -= 12;
        notes.push("At least one venue fails the health check.");
    }
    if (risk.venueConcentrationBreach) {
        score -= 10;
        notes.push("Primary venue concentration is above your allowed cap.");
    }
    if (risk.wrapperConcentrationBreach) {
        score -= 8;
        notes.push("Wrapper concentration is above your allowed cap.");
    }
    if (risk.bufferShortfallUsd > 0) {
        notes.push(`Stable buffer is short by $${roundUsd(risk.bufferShortfallUsd)}.`);
    }
    if (risk.sustainableMonthlyPayoutUsd < policy.monthlyPayoutTargetUsd) {
        notes.push("Requested payout is above the currently sustainable band.");
    }
    if (notes.length === 0) {
        notes.push("Policy is operating inside its target envelope.");
    }
    const normalizedScore = Math.round(clamp(score, 0, 100));
    let label = "Critical";
    if (normalizedScore >= 85) {
        label = "Strong";
    } else if (normalizedScore >= 70) {
        label = "Stable";
    } else if (normalizedScore >= 55) {
        label = "Guarded";
    } else if (normalizedScore >= 35) {
        label = "Fragile";
    }
    return {
        score: normalizedScore,
        label,
        notes
    };
}
export function projectPayoutBand(result) {
    const sustainable = result.decision.risk.sustainableMonthlyPayoutUsd;
    const target = result.input.policy.monthlyPayoutTargetUsd;
    if (sustainable <= 0) {
        return {
            lowUsd: 0,
            highUsd: 0
        };
    }
    const downsideBuffer = {
        ["Quiet"]: 0.05,
        ["Trend"]: 0.07,
        ["Stress"]: 0.10,
        ["Crisis"]: 0.14
    }[result.decision.regime];
    const lowUsd = roundUsd(Math.max(0, sustainable * (1 - downsideBuffer)));
    const highUsd = roundUsd(Math.min(target, sustainable * (1 + downsideBuffer * 0.55)));
    return {
        lowUsd: Math.min(lowUsd, highUsd),
        highUsd: Math.max(lowUsd, highUsd)
    };
}
export function deriveShadowScenarioHorizonDays(scenario) {
    const explicit = Math.round(Number(scenario.horizonDays));
    if (Number.isFinite(explicit) && explicit > 0) {
        return clamp(explicit, 1, 365);
    }
    return Math.round(clamp(SHADOW_BASE_HORIZON_DAYS + Math.max(0, scenario.drawdownPct) * 120, SHADOW_BASE_HORIZON_DAYS, SHADOW_MAX_HORIZON_DAYS));
}
function createZeroEconomics(horizonDays, borrowApr = 0) {
    return {
        horizonDays,
        borrowApr: roundPct(Math.max(0, borrowApr)),
        carryCostUsd: 0,
        rebalanceCostUsd: 0,
        liquidationPenaltyUsd: 0,
        liquidationTriggered: false,
        totalDragUsd: 0
    };
}
function withTotalDrag(economics) {
    return {
        ...economics,
        totalDragUsd: roundUsd(Math.max(0, economics.carryCostUsd + economics.rebalanceCostUsd + economics.liquidationPenaltyUsd))
    };
}
export function computeEffectiveBorrowApr(rail, stressedUtilization) {
    const flat = clamp(rail?.borrowApr ?? 0, 0, 1);
    if (!rail) return flat;
    const hasKink = typeof rail.irBaseApr === "number" && typeof rail.irSlope1 === "number" && typeof rail.irSlope2 === "number" && typeof rail.irKinkUtilization === "number";
    if (!hasKink) return flat;
    const baseUtilization = clamp(typeof stressedUtilization === "number" ? stressedUtilization : rail.utilizationRate ?? 0, 0, 1);
    const kink = clamp(rail.irKinkUtilization, 0.05, 0.98);
    const base = Math.max(0, rail.irBaseApr);
    const slope1 = Math.max(0, rail.irSlope1);
    const slope2 = Math.max(0, rail.irSlope2);
    if (baseUtilization <= kink) {
        return clamp(base + baseUtilization * slope1, 0, 2);
    }
    return clamp(base + kink * slope1 + (baseUtilization - kink) * slope2, 0, 2);
}
export function applyScenarioStressEconomics(input, scenario, primaryRail) {
    const horizonDays = deriveShadowScenarioHorizonDays(scenario);
    const drawdownPct = clamp(scenario.drawdownPct, 0, 0.9);
    const baseUtilization = clamp(primaryRail?.utilizationRate ?? 0, 0, 1);
    const stressedUtilization = clamp(baseUtilization + drawdownPct * 0.25, 0, 1);
    const borrowApr = computeEffectiveBorrowApr(primaryRail, stressedUtilization);
    let nextPortfolio = {
        ...input.portfolio
    };
    let liquidationPenaltyUsd = 0;
    let liquidationTriggered = false;
    let carryCostUsd = 0;
    const liquidationThreshold = clamp(Math.min(input.policy.maxLtv, primaryRail?.maxLtv ?? input.policy.maxLtv), 0.05, 0.95);
    const liquidationPenaltyRate = clamp((SHADOW_LIQUIDATION_PENALTY_BPS_BASE + Math.max(0, scenario.drawdownPct) * SHADOW_LIQUIDATION_PENALTY_BPS_DRAW) / 10000, 0.03, 0.12);
    const PARTIAL_LIQ_CAP_PCT = 0.5;
    const MAX_LIQ_PASSES = 3;
    function runLiquidationCascade(portfolio) {
        let pf = portfolio;
        let penalty = 0;
        let triggered = false;
        for(let pass = 0; pass < MAX_LIQ_PASSES; pass += 1){
            const currentLtv = safeDiv(pf.debtUsd, pf.collateralUsd);
            if (!Number.isFinite(currentLtv) || currentLtv <= liquidationThreshold || pf.debtUsd <= 0 || pf.collateralUsd <= 0) {
                break;
            }
            const excessDebtUsd = Math.max(0, pf.debtUsd - pf.collateralUsd * liquidationThreshold);
            const denominator = 1 - liquidationThreshold * (1 + liquidationPenaltyRate);
            if (excessDebtUsd <= 0 || denominator <= 0.02) {
                break;
            }
            const unconstrainedRepayUsd = excessDebtUsd / denominator;
            const passCapUsd = PARTIAL_LIQ_CAP_PCT * pf.debtUsd;
            const forcedRepayUsd = roundUsd(clamp(Math.min(unconstrainedRepayUsd, passCapUsd), 0, pf.debtUsd));
            if (forcedRepayUsd <= 0) {
                break;
            }
            const passPenaltyUsd = roundUsd(forcedRepayUsd * liquidationPenaltyRate);
            penalty = roundUsd(penalty + passPenaltyUsd);
            const collateralAfter = roundUsd(Math.max(0, pf.collateralUsd - forcedRepayUsd - passPenaltyUsd));
            const debtAfter = roundUsd(Math.max(0, pf.debtUsd - forcedRepayUsd));
            pf = {
                ...pf,
                btcUnits: pf.btcPriceUsd > 0 ? roundUnits(collateralAfter / pf.btcPriceUsd) : pf.btcUnits,
                collateralUsd: collateralAfter,
                debtUsd: debtAfter
            };
            triggered = true;
        }
        return {
            portfolio: pf,
            penaltyUsd: penalty,
            triggered
        };
    }
    const dailyRate = borrowApr / 365;
    const safeHorizonDays = Math.max(0, Math.floor(horizonDays));
    {
        const cascade = runLiquidationCascade(nextPortfolio);
        nextPortfolio = cascade.portfolio;
        liquidationPenaltyUsd = roundUsd(liquidationPenaltyUsd + cascade.penaltyUsd);
        if (cascade.triggered) liquidationTriggered = true;
    }
    for(let day = 1; day <= safeHorizonDays; day += 1){
        if (nextPortfolio.debtUsd <= 0) break;
        const accrual = nextPortfolio.debtUsd * dailyRate;
        carryCostUsd = roundUsd(carryCostUsd + Math.max(0, accrual));
        nextPortfolio = {
            ...nextPortfolio,
            debtUsd: roundUsd(nextPortfolio.debtUsd + accrual)
        };
        const cascade = runLiquidationCascade(nextPortfolio);
        if (cascade.triggered) {
            nextPortfolio = cascade.portfolio;
            liquidationPenaltyUsd = roundUsd(liquidationPenaltyUsd + cascade.penaltyUsd);
            liquidationTriggered = true;
        }
    }
    return {
        input: {
            ...input,
            portfolio: nextPortfolio
        },
        economics: withTotalDrag({
            horizonDays,
            borrowApr,
            carryCostUsd,
            rebalanceCostUsd: 0,
            liquidationPenaltyUsd,
            liquidationTriggered,
            totalDragUsd: 0
        })
    };
}
export function estimateActionRebalanceCostUsd(action, rail, portfolio) {
    const rebalanceCostBps = Math.max(0, Number(rail?.rebalanceCostBps || 0));
    if (!action || rebalanceCostBps <= 0) {
        return 0;
    }
    const amountUsd = Math.max(0, Number(action.amountUsd) || 0);
    let notionalUsd = 0;
    switch(action.type){
        case "BorrowForBuffer":
        case "PartialRepay":
        case "EmergencyDeRisk":
            notionalUsd = amountUsd;
            break;
        case "RotateVenue":
            notionalUsd = Math.max(0, Number(portfolio?.debtUsd) || 0);
            break;
        default:
            notionalUsd = 0;
            break;
    }
    return roundUsd(notionalUsd * rebalanceCostBps / 10000);
}
export function applyActionRebalanceCost(input, action, primaryRail, existingEconomics) {
    const economics = existingEconomics ? {
        ...existingEconomics
    } : createZeroEconomics(SHADOW_BASE_HORIZON_DAYS, primaryRail?.borrowApr ?? 0);
    const rebalanceCostUsd = estimateActionRebalanceCostUsd(action, primaryRail, input.portfolio);
    const existingRebalanceCostUsd = Math.max(0, Number(economics.rebalanceCostUsd) || 0);
    if (rebalanceCostUsd <= 0) {
        return {
            input,
            economics: withTotalDrag(economics)
        };
    }
    const cumulativeRebalanceCostUsd = roundUsd(existingRebalanceCostUsd + rebalanceCostUsd);
    const stableBufferAfterCostUsd = roundUsd(Math.max(0, input.portfolio.stableBufferUsd - rebalanceCostUsd));
    const unfundedCostUsd = roundUsd(Math.max(0, rebalanceCostUsd - input.portfolio.stableBufferUsd));
    return {
        input: {
            ...input,
            portfolio: {
                ...input.portfolio,
                stableBufferUsd: stableBufferAfterCostUsd,
                debtUsd: roundUsd(input.portfolio.debtUsd + unfundedCostUsd)
            }
        },
        economics: withTotalDrag({
            ...economics,
            rebalanceCostUsd: cumulativeRebalanceCostUsd
        })
    };
}
export function stressRailSnapshot(rail, drawdownPct) {
    const healthScore = clamp(rail.healthScore - drawdownPct * 0.30, 0.12, 1);
    return {
        ...rail,
        healthy: rail.healthy && healthScore >= 0.42,
        oracleConfidence: roundPct(clamp(rail.oracleConfidence - drawdownPct * 0.10, 0.40, 1)),
        liquidityScore: roundPct(clamp(rail.liquidityScore - drawdownPct * 0.24, 0.18, 1)),
        healthScore: roundPct(healthScore),
        borrowApr: roundPct(clamp(rail.borrowApr + drawdownPct * 0.045, 0.01, 0.3)),
        depositApr: roundPct(clamp(rail.depositApr + drawdownPct * 0.01, 0, 0.2)),
        maxLtv: roundPct(clamp(rail.maxLtv - drawdownPct * 0.035, 0.12, 0.85)),
        availableDebtUsd: roundUsd(Math.max(0, rail.availableDebtUsd * (1 - drawdownPct * 0.46))),
        rebalanceCostBps: roundBps(rail.rebalanceCostBps * (1 + drawdownPct * 1.1)),
        notes: [
            ...rail.notes,
            `Stress-adjusted at ${Math.round(drawdownPct * 100)}% BTC drawdown.`
        ]
    };
}
export function createShadowScenarioInput(baseInput, scenario) {
    const drawdownPct = clamp(scenario.drawdownPct, 0, 0.9);
    const oracleHaircut = clamp(scenario.oracleConfidenceHaircut ?? 0, 0, 0.95);
    const stableDepegPct = clamp(scenario.stableDepegPct ?? 0, 0, 0.5);
    const nextBtcPriceUsd = roundUsd(baseInput.portfolio.btcPriceUsd * (1 - drawdownPct));
    const nextCollateralUsd = roundUsd(baseInput.portfolio.btcUnits * nextBtcPriceUsd);
    const bufferDrainMultiplier = clamp(1 - drawdownPct * 0.45, 0.50, 1);
    const depegDrainedBuffer = baseInput.portfolio.stableBufferUsd * (1 - stableDepegPct);
    const nextStableBufferUsd = roundUsd(depegDrainedBuffer * bufferDrainMultiplier);
    const venueSet = baseInput.venues.length > 0 ? baseInput.venues : [
        defaultVenue()
    ];
    return {
        ...baseInput,
        portfolio: {
            ...baseInput.portfolio,
            btcPriceUsd: nextBtcPriceUsd,
            collateralUsd: nextCollateralUsd,
            stableBufferUsd: nextStableBufferUsd,
            debtUsd: baseInput.portfolio.debtUsd
        },
        market: {
            realizedVol30d: roundPct(clamp(Math.max(baseInput.market.realizedVol30d, 0.42 + drawdownPct * 2.6), 0.2, 2.5)),
            dailyMovePctAbs: roundPct(clamp(Math.max(baseInput.market.dailyMovePctAbs, 0.012 + drawdownPct * 0.22), 0.005, 0.2)),
            weeklyDrawdownPct: roundPct(clamp(Math.max(baseInput.market.weeklyDrawdownPct, drawdownPct), 0, 0.6)),
            trendStrength: roundPct(clamp(Math.max(baseInput.market.trendStrength, 0.30 + drawdownPct * 1.1), 0, 1))
        },
        venues: venueSet.map((venue)=>{
            const healthScore = clamp(venue.healthScore - drawdownPct * 0.42, 0.12, 1);
            const oracleConfidence = roundPct(clamp(venue.oracleConfidence - drawdownPct * 0.12 - oracleHaircut, 0, 1));
            return {
                ...venue,
                healthy: venue.healthy && healthScore >= 0.42 && oracleConfidence >= 0.45,
                oracleConfidence,
                liquidityScore: roundPct(clamp(venue.liquidityScore - drawdownPct * 0.34, 0.18, 1)),
                healthScore: roundPct(healthScore)
            };
        })
    };
}
export class ShadowModeSimulator {
    engine = new TideEngine();
    railAdapters;
    railAggregator = new RailSnapshotAggregator();
    railAllocator = new RailAllocator();
    constructor(railAdapters = createStarterRailAdapters()){
        this.railAdapters = railAdapters;
    }
    async simulate(baseInput, scenarios = DEFAULT_SHADOW_SCENARIOS) {
        const baseContext = {
            now: baseInput.now,
            policy: baseInput.policy,
            portfolio: baseInput.portfolio,
            market: baseInput.market
        };
        const { snapshots: baseRails, warnings: adapterWarnings } = await this.railAggregator.collect(this.railAdapters, baseContext);
        const outcomes = [];
        for (const scenario of scenarios){
            const rawInput = createShadowScenarioInput(baseInput, scenario);
            const stressedRails = baseRails.map((rail)=>stressRailSnapshot(rail, scenario.drawdownPct));
            const allocation = this.railAllocator.allocate({
                now: rawInput.now,
                policy: rawInput.policy,
                portfolio: rawInput.portfolio,
                market: rawInput.market
            }, stressedRails, adapterWarnings);
            const effectiveInput = applyRailToInput(rawInput, allocation);
            const primaryRail = allocation.primary?.rail;
            const stressModeled = applyScenarioStressEconomics(effectiveInput, scenario, primaryRail);
            let result = await this.engine.tick(stressModeled.input, {
                execute: false
            });
            let accumulatedEconomics = stressModeled.economics;
            let lastActionType = result.decision.chosen?.type;
            const MAX_REBALANCE_PASSES = 3;
            for(let pass = 0; pass < MAX_REBALANCE_PASSES; pass += 1){
                const previousRebalanceCostUsd = Math.max(0, accumulatedEconomics.rebalanceCostUsd || 0);
                const nextCost = applyActionRebalanceCost(result.input, result.decision.chosen, primaryRail, accumulatedEconomics);
                const incrementalRebalanceCostUsd = roundUsd(nextCost.economics.rebalanceCostUsd - previousRebalanceCostUsd);
                accumulatedEconomics = nextCost.economics;
                if (incrementalRebalanceCostUsd <= 0) {
                    break;
                }
                result = await this.engine.tick(nextCost.input, {
                    execute: false
                });
                const nextActionType = result.decision.chosen?.type;
                if (nextActionType === lastActionType || !nextActionType) {
                    break;
                }
                lastActionType = nextActionType;
            }
            outcomes.push(this.createOutcome(scenario, result, allocation, accumulatedEconomics));
        }
        const baseline = outcomes[0];
        if (!baseline) {
            throw new Error("Shadow Mode requires at least one scenario.");
        }
        const uniqueActions = [];
        for (const outcome of outcomes){
            const alreadyIncluded = uniqueActions.some((action)=>action.type === outcome.result.decision.chosen.type);
            if (!alreadyIncluded) {
                uniqueActions.push(outcome.result.decision.chosen);
            }
        }
        const breakwaterTrigger = outcomes.find((outcome)=>outcome.scenario.drawdownPct > 0 && OPERATING_STATE_SEVERITY[outcome.operatingState] >= OPERATING_STATE_SEVERITY["DeRisk"])?.scenario.drawdownPct ?? null;
        const worstOperatingState = outcomes.reduce((worst, outcome)=>{
            return OPERATING_STATE_SEVERITY[outcome.operatingState] > OPERATING_STATE_SEVERITY[worst] ? outcome.operatingState : worst;
        }, "Observe");
        const sustainableValues = outcomes.map((outcome)=>outcome.result.decision.risk.sustainableMonthlyPayoutUsd);
        const liquidationOutcome = outcomes.reduce((worst, outcome)=>{
            if (!outcome.economics.liquidationTriggered) {
                return worst;
            }
            if (!worst) {
                return outcome;
            }
            return outcome.economics.liquidationPenaltyUsd > worst.economics.liquidationPenaltyUsd ? outcome : worst;
        }, null);
        const railWarnings = [
            ...new Set(outcomes.flatMap((outcome)=>outcome.allocation?.warnings ?? []))
        ];
        const liveRailCount = baseRails.filter((rail)=>rail.source !== "fixture").length;
        const railDataMode = liveRailCount === 0 ? "fixture" : liveRailCount === baseRails.length ? "live" : "mixed";
        const railUpdateTimestamps = baseRails.map((rail)=>Date.parse(rail.updatedAt)).filter((value)=>Number.isFinite(value) && value > 0);
        const oldestRailUpdateAt = railUpdateTimestamps.length > 0 ? new Date(Math.min(...railUpdateTimestamps)).toISOString() : undefined;
        const freshestRailUpdateAt = railUpdateTimestamps.length > 0 ? new Date(Math.max(...railUpdateTimestamps)).toISOString() : undefined;
        return {
            generatedAt: new Date().toISOString(),
            baseline,
            scenarios: outcomes,
            summary: {
                survivablePayoutBandLowUsd: roundUsd(minValue(sustainableValues)),
                survivablePayoutBandHighUsd: roundUsd(Math.max(baseline.result.decision.risk.sustainableMonthlyPayoutUsd, minValue(sustainableValues))),
                currentLtv: roundPct(baseline.result.decision.risk.ltv),
                bufferCoverageDays: Math.round(baseline.bufferCoverageDays),
                baselineHorizonDays: baseline.economics.horizonDays,
                baselineCarryCostUsd: baseline.economics.carryCostUsd,
                baselineRebalanceCostUsd: baseline.economics.rebalanceCostUsd,
                breakwaterTriggerDrawdownPct: breakwaterTrigger,
                averageHealthScore: Math.round(average(outcomes.map((outcome)=>outcome.health.score))),
                worstOperatingState,
                worstCaseTotalDragUsd: roundUsd(Math.max(...outcomes.map((outcome)=>outcome.economics.totalDragUsd))),
                worstCaseLiquidationPenaltyUsd: roundUsd(Math.max(...outcomes.map((outcome)=>outcome.economics.liquidationPenaltyUsd))),
                liquidationScenarioLabel: liquidationOutcome?.scenario.label,
                projectedTideFeeBpsAnnual: TIDE_PLATFORM_FEE_BPS_ANNUAL,
                projectedTideFeeUsd30d: roundUsd(Math.max(0, baseline.result.input.portfolio.debtUsd) * (TIDE_PLATFORM_FEE_BPS_ANNUAL / 10_000) * (30 / 365)),
                projectedTideFeePctOfPayout: roundPct(baseline.result.input.policy.monthlyPayoutTargetUsd > 0 ? Math.max(0, baseline.result.input.portfolio.debtUsd) * (TIDE_PLATFORM_FEE_BPS_ANNUAL / 10_000) * (30 / 365) / baseline.result.input.policy.monthlyPayoutTargetUsd : 0),
                actionExamples: uniqueActions.slice(0, 4),
                primaryRailId: baseline.allocation?.primary?.rail.id,
                primaryRailName: baseline.allocation?.primary?.rail.name,
                backupRailId: baseline.allocation?.backup?.rail.id,
                backupRailName: baseline.allocation?.backup?.rail.name,
                railWarnings: railWarnings.slice(0, 6),
                railDataMode,
                railCount: baseRails.length,
                liveRailCount,
                oldestRailUpdateAt,
                freshestRailUpdateAt
            }
        };
    }
    createOutcome(scenario, result, allocation, economics = createZeroEconomics(deriveShadowScenarioHorizonDays(scenario))) {
        const operatingState = deriveOperatingState(result.input, result.decision);
        const health = evaluatePolicyHealth(result.input, result.decision);
        const payoutBand = projectPayoutBand(result);
        const bufferCoverageMonths = calculateBufferCoverageMonths(result.input.portfolio.stableBufferUsd, result.input.policy.monthlyPayoutTargetUsd);
        return {
            scenario,
            operatingState,
            health,
            payoutBandLowUsd: payoutBand.lowUsd,
            payoutBandHighUsd: payoutBand.highUsd,
            bufferCoverageMonths,
            bufferCoverageDays: roundUsd(bufferCoverageMonths * 30.4),
            economics,
            result,
            allocation
        };
    }
}
async function demo() {
    const engine = new TideEngine();
    const input = {
        now: new Date().toISOString(),
        policy: {
            mode: "Income",
            priority: "BTCPreservation",
            maxLtv: 0.32,
            targetLtvLow: 0.18,
            targetLtvHigh: 0.24,
            minStableBufferUsd: 1500,
            desiredRunwayMonths: 3,
            monthlyPayoutTargetUsd: 500,
            allowPayoutPauseInStress: true,
            maxSingleVenueExposurePct: 0.70,
            maxWrapperExposurePct: 0.80,
            autoRepayLtv: 0.27,
            emergencyLtv: 0.30,
            minOracleConfidence: 0.90,
            minLiquidityScore: 0.75,
            allowNewBorrowInStress: false,
            allowNewBorrowInCrisis: false
        },
        portfolio: {
            btcUnits: 1.0,
            btcPriceUsd: 90000,
            collateralUsd: 90000,
            debtUsd: 22000,
            stableBufferUsd: 800,
            venueExposurePct: 0.65,
            wrapperExposurePct: 0.70
        },
        market: {
            realizedVol30d: 0.88,
            dailyMovePctAbs: 0.042,
            weeklyDrawdownPct: 0.09,
            trendStrength: 0.58
        },
        venues: [
            {
                name: "PrimaryRail",
                healthy: true,
                oracleConfidence: 0.95,
                liquidityScore: 0.82,
                healthScore: 0.88
            }
        ]
    };
    const result = await engine.tick(input, {
        execute: false
    });
    return result;
}
if (typeof require !== "undefined" && typeof module !== "undefined" && require.main === module) {
    demo().catch(()=>{
        process.exit(1);
    });
}
