import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import * as nodeModule from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const currentDir = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(currentDir, "..");
const sourcePath = resolve(rootDir, "tide_core.ts");
const outputPath = resolve(rootDir, "shadow-mode/lib/tide_core.mjs");
const require = createRequire(import.meta.url);
const stripTypeScriptTypes = nodeModule.stripTypeScriptTypes;

const source = readFileSync(sourcePath, "utf8");

function transformTypeScript(sourceText, inputPath) {
  if (typeof stripTypeScriptTypes === "function") {
    return stripTypeScriptTypes(sourceText, {
      mode: "transform",
    });
  }

  const ts = require("typescript");
  const transpiled = ts.transpileModule(sourceText, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      verbatimModuleSyntax: true,
      removeComments: false,
    },
    fileName: inputPath,
    reportDiagnostics: true,
  });

  if (Array.isArray(transpiled.diagnostics) && transpiled.diagnostics.length) {
    const host = {
      getCanonicalFileName: (fileName) => fileName,
      getCurrentDirectory: () => rootDir,
      getNewLine: () => "\n",
    };
    const message = ts.formatDiagnosticsWithColorAndContext(transpiled.diagnostics, host);
    throw new Error(`TypeScript transpile failed for ${inputPath}\n${message}`);
  }

  return transpiled.outputText;
}

const transformed = transformTypeScript(source, sourcePath);

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by shadow-mode/build.mjs\n${transformed}`,
  "utf8"
);

console.log(`Built ${outputPath}`);
