import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const currentDir = dirname(fileURLToPath(import.meta.url));
const sourceDir = resolve(currentDir, "styles-src");

mkdirSync(sourceDir, { recursive: true });

const sourceFiles = readdirSync(sourceDir)
  .filter((fileName) => fileName.endsWith(".css"))
  .sort((left, right) => left.localeCompare(right));

if (!sourceFiles.length) {
  throw new Error(`No CSS sources found in ${sourceDir}`);
}

const banner = [
  "/* =======================================================================",
  "   Generated by shadow-mode/build-styles.mjs",
  "   Source of truth: shadow-mode/styles-src/*.css",
  "   Do not edit generated CSS in shadow-mode/*.css directly.",
  "   ======================================================================= */",
  "",
].join("\n");

const cssByFile = new Map(
  sourceFiles.map((fileName) => [fileName, readFileSync(resolve(sourceDir, fileName), "utf8").trimEnd()])
);

const bundleFiles = {
  "styles-workspace.css": [
    "00-foundation-shell.css",
    "10-results-workspace.css",
    "90-runtime-polish.css",
  ],
  // styles-readout.css is shared between /live, /results, and the
  // /design-system playground. Was previously emitted twice as
  // byte-identical styles-live.css + styles-results.css (~221 KB each)
  // — operators going /live → /results re-downloaded the same bundle.
  // Per perf §15 + Phase B.4. The two routes now reference one file
  // and browsers cache once.
  "styles-readout.css": [
    "00-foundation-shell.css",
    "10-results-workspace.css",
    "20-live.css",
    "30-scenario-chart.css",
    "90-runtime-polish.css",
  ],
  "styles-setup.css": [
    "00-foundation-shell.css",
    "30-scenario-chart.css",
    "98-setup-rebuild.css",
  ],
};

for (const [bundleName, files] of Object.entries(bundleFiles)) {
  const missing = files.filter((fileName) => !cssByFile.has(fileName));
  if (missing.length) {
    throw new Error(`Bundle ${bundleName} references missing CSS sources: ${missing.join(", ")}`);
  }

  const sections = files.map((fileName) => {
    const css = cssByFile.get(fileName);
    return [
      `/* >>> ${fileName} >>> */`,
      css,
    ].join("\n");
  });

  const outputPath = resolve(currentDir, bundleName);
  const output = `${banner}${sections.join("\n\n")}\n`;
  writeFileSync(outputPath, output, "utf8");
}

console.log(`Built ${Object.keys(bundleFiles).length} CSS bundles from ${sourceFiles.length} source files.`);
